
export const WEATHER_LIST_REQUEST = 'WEATHER_LIST_REQUEST'
export const WEATHER_LIST_SUCCESS = 'WEATHER_LIST_SUCCESS'
export const WEATHER_LIST_FAIL = 'WEATHER_LIST_FAIL'


export const FORECAST_LIST_REQUEST = 'FORECAST_LIST_REQUEST'
export const FORECAST_LIST_SUCCESS = 'FORECAST_LIST_SUCCESS'
export const FORECAST_LIST_FAIL = 'FORECAST_LIST_FAIL'